Repository 2024-Winter-Bootcamp-TeamC/InSideOut-Frontend, pull requests merged in 2025-01, with the labels that each got.

#6 [Design] : 보고서 목록 버튼
  package-lock.json
  package.json
  src/assets/Report.svg
  src/component/Button/HomeButton.css
  src/component/Button/HomeButton.jsx
  src/component/Button/ReportButton.jsx
Labels: 🎨 Design

#11 [Design] : 캐릭터 프레임 컴포넌트 만들기
  src/component/CharacterFrame.jsx
Labels: 🎨 Design

#9 [Design] : 감정구슬 카테고리 컴포넌트 만들기
  src/component/Button/CategoryButton.jsx
  src/fonts/BMHANNAPro.ttf
Labels: 🎨 Design

#17 [CHORE] dev에 push하면 이슈 자동 닫힘
  .github/workflows/close-issue-on-dev.yml
Labels: 🧭 Chore

#18 [Design] : 카테고리 이미지 프레임 만들기
  src/component/category/CategoryImageFrame.jsx
Labels: 🎨 Design

#7 [Design] : 뒤로가기 컴포넌트 만들기
  src/component/BackButton/BackButton.css
  src/component/BackButton/BackButton.jsx
Labels: 🎨 Design

#26 [DESGIN] 로그인 페이지 퍼블리싱
  public/assets/HomeButton.gif
  src/App.jsx
  src/assets/HomeButton.gif
  src/index.css
  src/pages/login.jsx
  src/styles/GlobalStyle.js
  vite.config.js
Labels: 🎨 Design

#31 [Refactor] : 페이지 이름 변경 및 위치 수정
  src/component/buttons/BackButton.css
  src/component/buttons/BackButton.jsx
  src/component/buttons/CategoryButton.jsx
  src/component/buttons/HomeButton.css
  src/component/buttons/HomeButton.jsx
  src/component/buttons/ReportButton.jsx
  src/component/category/CategoryImageFrame.jsx
  src/component/categorypage/CategoryImageFrame.jsx
  src/pages/category.jsx
Labels: 🧹 Refactor

#33 [DESIGN] 준비 페이지 퍼블리싱
  src/assets/preparation.png
  src/assets/text.png
  src/assets/text1.png
  src/component/Button/BackButton.css
  src/component/Button/BackButton.jsx
  src/component/ImageAttachFrame.jsx
  src/pages/preparation.jsx
Labels: 🎨 Design

#35 [DESGIN] 보고서 목록 페이지 퍼블리싱
  src/App.jsx
  src/assets/reportlistpage/BackGround.png
  src/assets/reportlistpage/CompanyObject.png
  src/assets/reportlistpage/FamilyObject.png
  src/assets/reportlistpage/FriendsObject.png
  src/assets/reportlistpage/LoveObject.png
  src/component/buttons/CategoryButton.jsx
  src/component/buttons/HomeButton.css
  src/component/buttons/HomeButton.jsx
  src/pages/reportlist.jsx
Labels: 🎨 Design

#37 [Design] : 감정 선택 페이지 퍼블리싱
  src/assets/emotionselect/Anger.png
  src/assets/emotionselect/Anxiety.png
  src/assets/emotionselect/Disgust.png
  src/assets/emotionselect/Embarrassment.png
  src/assets/emotionselect/Fear.png
  src/assets/emotionselect/Joy.png
  src/assets/emotionselect/Sadness.png
  src/component/emotionselect/BackLight.jsx
  src/component/emotionselect/TextFrame.jsx
  src/pages/EmotionSelect.jsx
Labels: 🎨 Design

#40 [Design] 보고서 상세 페이지 퍼블리싱
  package-lock.json
  package.json
  src/assets/HomeButton.gif
  src/assets/HomeButton.svg
  src/assets/ReportDetail.jpg
  src/assets/기쁨이.png
  src/assets/까칠이.png
  src/assets/당황이.png
  src/assets/버럭이.png
  src/assets/불안이.png
  src/assets/소심이.png
  src/assets/슬픔이.png
  src/component/Button/BackButton.css
  src/component/Button/BackButton.jsx
  src/fonts/BMHANNAPro.ttf
  src/pages/ReportDetail.jsx
Labels: 🎨 Design

#39 [Design] : 디스코드 채팅 페이지 퍼블리싱
  src/assets/ChatRoom/Anger.png
  src/assets/ChatRoom/Anxiety.png
  src/assets/ChatRoom/BackGround.png
  src/assets/ChatRoom/Disgust.png
  src/assets/ChatRoom/Embarrassment.png
  src/assets/ChatRoom/Fear.png
  src/assets/ChatRoom/Joy.png
  src/assets/ChatRoom/ModelSelect.svg
  src/assets/ChatRoom/PaperAirPlane.svg
  src/assets/ChatRoom/Riley.png
  src/assets/ChatRoom/Sadness.png
  src/component/CharacterFrame.jsx
  src/component/ChatRoom/CharacterFrame.jsx
  src/component/ChatRoom/ChatFinishModal.jsx
  src/pages/ChatRoom.jsx
Labels: 🎨 Design

#46 [Chore] : Axios패키지 다운
  package-lock.json
  package.json
Labels: 🧭 Chore

#47 [Desgin] 폰트 수정, 버튼 수정
  src/pages/login.jsx
Labels: 🎨 Design

#51 [Feat] : 로그인 페이지 API연동
  src/pages/category.jsx
  src/pages/login.jsx
Labels: 🚀 Feat

#53 [Feat] : 보고서 목록페이지 모든 보고서 목록 조회 API 연동
  src/App.jsx
  src/pages/reportlist.jsx
Labels: 🚀 Feat

#59 [Feat] : 감정 선택 페이지 API 연동
  src/pages/EmotionSelect.jsx
Labels: 🚀 Feat

#56 [DESIGN] : 감정 선택 페이지 디자인 수정
  src/pages/EmotionSelect.jsx
Labels: 🎨 Design

#63 [Design] : 디자인 수정
  src/component/buttons/CategoryButton.jsx
  src/component/buttons/HomeButton.css
  src/component/buttons/ReportButton.jsx
  src/pages/preparation.jsx
Labels: 🎨 Design

#65 [Design] : BGM 추가
  src/App.jsx
  src/assets/BackGroundBGM.mp3
  src/assets/Mute.png
  src/assets/Volume.png
  src/pages/ChatRoom.jsx
Labels: 🎨 Design

#71 [FEAT] 보고서 상세 페이지 api 연동
  src/pages/ReportDetail.jsx
  src/pages/reportlist.jsx
Labels: 🚀 Feat

#74 [Design] : 보고서 목록 페이지 디자인 수정 및 보고서 상세 페이지 버튼 기능 수정
  src/pages/ReportDetail.jsx
  src/pages/reportlist.jsx
Labels: 🎨 Design

#76 [Design] : 페이지 디테일 추가
  src/component/emotionselect/BackLight.jsx
  src/pages/reportlist.jsx
Labels: 🎨 Design

#80 [Design] : 로그인 페이지 구조 수정
  src/component/StarrySky.jsx
Labels: 🎨 Design

#82 Design : BGM 소리 줄이기
  src/App.jsx
Labels: 🎨 Design

#86 [Design] : 카테고리에서 준비 페이지로 넘어가는 모달창 만들기
  src/component/category/CategoryImageFrame.jsx
  src/pages/category.jsx
Labels: 🎨 Design

#89 Design/#85
  src/component/ChatRoom/CharacterFrame.jsx
  src/component/ChatRoom/ChatFinishModal.jsx
  src/component/category/CategoryImageFrame.jsx
  src/component/loading.jsx
  src/pages/ChatRoom.jsx
  src/pages/ReportDetail.jsx
  src/pages/category.jsx
  src/pages/reportlist.jsx
Labels: 🎨 Design

#88 [Design] : 부럽이로 디자인 수정
  src/assets/ChatRoom/Embarrassment.png
  src/assets/emotionselect/Embarrassment.png
  src/assets/당황이.png
  src/component/emotionselect/BackLight.jsx
  src/component/emotionselect/TextFrame.jsx
  src/pages/ChatRoom.jsx
  src/pages/EmotionSelect.jsx
  src/pages/ReportDetail.jsx
  src/pages/category.jsx
Labels: 🎨 Design
